<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>TheWarriorsFreecam</RootNamespace>
    <AssemblyName>TheWarriorsFreecam</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TheWarriorsFreecam.Core\TheWarriorsFreecam.Core.csproj" />
  </ItemGroup>
</Project>
